server:
  port: 8081

spring:
  application:
    name: smartCast
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/smart_cast
    username: postgres
    password: 123
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    hibernate:
      ddl-auto: update

application:
  security:
    jwt:
      secret-key: 743777217A25432A462D4A614E635266556A586E3272357538782F413F442847
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

logging:
  level:
    org:
    springframework:
      security: DEBUG
      web: DEBUG
      data: DEBUG
      hibernate: DEBUG
      jpa: DEBUG
      sql: DEBUG
      jwt: DEBUG


baseUrl: http://localhost:8081